### ISSUE TITLE
Grass/Podzol can sometimes generate underwater

### ISSUE THREAD

**Issue by Apollounknowndev** [Cristelknight/Expanded-Ecosphere#1]
Seed: 3142012640407748298
Coordinates: -12 66 89
Screenshot:
![image](https://user-images.githubusercontent.com/102649729/198920909-627608dc-c320-4ee8-9061-5f4055c772b4.png)

**Comment by Cristelknight** [comment]
Known issue. Will maybe be fixed one day or not, because it is not that important.
