### ISSUE TITLE
[1.19.2] Fabric : cant see config in game

### ISSUE THREAD

**Issue by zeid0ne** [Cristelknight/Expanded-Ecosphere#10]
Hi, i cant see config for your mod in modmenu, but i can see the config of other mods.

modMenu version : 4.0.6

your version : 3.1.8

Cloth config : 9.0.92

Fabric api : 0.67.1

Fabric loader : 0.14.10

Thanks

![image](https://user-images.githubusercontent.com/38461940/204101482-c8b13196-14f7-4bab-9159-a033bc60766d.png)

**Comment by Cristelknight** [comment]
Could you send a log?

**Comment by zeid0ne** [comment]
Updated all my mods and loaders and its ok now
