### ISSUE TITLE
Snow in badlands

### ISSUE THREAD

**Issue by bota66** [Cristelknight/Expanded-Ecosphere#100]
When I put in this mod, there is snow in the badlands. Snow and snow blocks. The loader and the version: forge, 1.20.1
![a](https://github.com/Cristelknight999/Expanded-Ecosphere/assets/124189302/5ddc1c5e-036d-4cd9-97ee-9d37ec4d5cd3)

**Comment by Doming3000** [comment]
Same here

**Comment by Cristelknight** [comment]
this is intentional. if you don't want it, remove the frost layer from the biome file
