### ISSUE TITLE
Can't create superflat worlds.

### ISSUE THREAD

**Issue by Doming3000** [Cristelknight/Expanded-Ecosphere#102]
No matter how many times I select that I want a flat world, when creating the world it is generated as a normal one.

Out of curiosity I decided to disable the mod, then create my flat world and re-enable the mod to see what happened, exactly what I expected happened:

![2024-07-13_14 25 51](https://github.com/user-attachments/assets/0009cac8-eab3-4760-b1dc-001392767200)

**Comment by Cristelknight** [comment]
this is a minecraft issue. just play without wee if you need a flat world and pre-gen it
