### ISSUE TITLE
hexerei conflicts with expanded ecosphere 1.20.1 / 3.2.4

### ISSUE THREAD

**Issue by CobaltGlacier** [Cristelknight/Expanded-Ecosphere#105]
whenever i play with both mods, it gives me some error about a feature cycle.
[crash-2024-07-25_22.50.12-server.txt](https://github.com/user-attachments/files/16386345/crash-2024-07-25_22.50.12-server.txt)

idk what causes this issue, it has something to do with vines, but can someone take a look at it

**Comment by Cristelknight** [comment]
Known issue. But I'm pretty sure it's an issue on there side. Maybe also create an issue there

**Comment by Cristelknight** [comment]
#107
