### ISSUE TITLE
Island biomes generate as oceans

### ISSUE THREAD

**Issue by metroHD** [Cristelknight/Expanded-Ecosphere#106]
the island biomes (desert island, mushroom island/fields, mediterranean island, jungle island) generate underwater. they have the appearance of average oceans and contain no vegetation, however structures still spawn

![image](https://github.com/user-attachments/assets/74432050-dd12-4601-9c47-0f560bfe0025)
^ the debug menu shows that the current biome is 'desert island', however the terrain is underwater like an ocean biome. (the structures in the background are there because the biome is technically a desert (and they spawn in a desert).)

![image](https://github.com/user-attachments/assets/3a7d6fec-86b6-44aa-b885-3250b337efbd)
^ world map image, the 'mediterranean island thermal spring' (it is where the cursor is) biome is underwater.

![image](https://github.com/user-attachments/assets/afcc4a26-01d4-470f-aa5b-9ef5feb0cff7)
^ sparse jungle tree generated (somehow) underwater, with the treetop being above the water surface

Mods: (Forge version 1.20.1-47.2.17)
	- amendments 1.20-1.1.18
	- appleskin 2.5.1+mc1.20.1
	- architectury 9.2.14
	- farmersdelight 1.20.1-1.2.4
	- ferritecore 6.0.1
	- flywheel 0.6.10-7
	- forge 47.2.17
	- functionalstorage 1.20.1-1.2.10
	- garnished 1.7.2+1.20.1
	- geckolib 4.4.4
	- gravestone 1.20.1-1.0.15
	- hole_filler_mod 1.2.8
	- immersive_paintings 0.6.7+1.20.1
	- interiors 0.5.3+forge-mc1.20.1
	- jade 11.9.3+forge
	- jei 15.3.0.4
	- kambrik 6.1.1+1.20.1
	- konkrete 1.8.0
	- kotlinforforge 4.10.0
	- mcwbridges 3.0.0
	- mcwfurnitures 3.2.2
	- mcwpaths 1.0.4
	- memoryleakfix 1.1.5
	- minecraft 1.20.1
	- mixinextras 0.3.5
	- mixinsquared 0.1.1
	- modelfix 1.15
	- modernfix 5.15.0+mc1.20.1
	- moonlight 1.20-2.11.12
	- mr_dungeons_andtaverns 3.0.3.f
	- nochatreports 1.20.1-v2.2.2
	- numismatics 1.0.3+forge-mc1.20.1
	- openpartiesandclaims 0.22.0
	- puzzlesaccessapi 8.0.7
	- puzzleslib 8.1.18
	- radiantgear 2.1.4+1.20.1
	- railways 1.6.1+forge-mc1.20.1
	- resourcefullib 2.1.24
	- rubidium 0.7.1
	- searchables 1.0.2
	- shulkerboxslot 5.1.1+1.20.1
	- sliceanddice 3.2.0
	- spectrelib 0.13.15+1.20.1
	- spyglass_of_curios 1.7.2
	- supermartijn642configlib 1.1.8
	- supermartijn642corelib 1.1.17
	- supplementaries 1.20-2.8.10
	- tectonic 2.3.4
	- tfmg 0.8.0b
	- titanium 3.8.27
	- veinmining 1.4.0+1.20.1
	- voicechat 1.20.1-2.5.12
	- world_preview 1.3.0
	- worldedit 7.2.15+6463-5ca4dff
	- wormhole 1.1.16
	- xaerominimap 24.0.3
	- xaeroworldmap 1.38.1
	- yungsapi 1.20-Forge-4.0.4
	- yungsbridges 1.20-Forge-4.0.3
	- yungsextras 1.20-Forge-4.0.3

**Comment by Cristelknight** [comment]
WWEE isn't really compatible with tectonic. That's why it won't work 100% correct
