### ISSUE TITLE
Large biomes terrain error after rejoining world

### ISSUE THREAD

**Issue by Creeprhuntr76** [Cristelknight/Expanded-Ecosphere#11]
I've encountered this issue where the unexplored terrain will revert to normal gen instead of large biomes after rejoining a world.

I start a new world, select large biomes & no structures
The first time in the world everything seems to generate normally (large biomes)
I quit and rejoin
during the loading of the world it gives an error and displays the "Experimental worlds will not be supported" message
All unexplored areas revert to _**not**_ large biomes
it leaves a very ugly border that is visible on the map

I'm sorry if this is an issue on my end that I'm just too dumb to see or there's a mod incompatibility, but I've tested this with only WWOO installed and it seems to do the same thing. 

Examples:
![2022-11-26_11 22 31](https://user-images.githubusercontent.com/77077091/204105791-1dad577a-b954-44b8-a447-db775338123a.png)
![2022-11-26_11 22 41](https://user-images.githubusercontent.com/77077091/204105797-32e5244c-deff-4b45-b81b-3c38719e2863.png)
![2022-11-26_11 23 15](https://user-images.githubusercontent.com/77077091/204105812-7f00b4a8-c8f3-4be4-a6ef-bd2f3e7c5a08.png)

**Comment by Rezois** [comment]
Having the exact same issue, spent the last like 4 hours trying to narrow it down, glad to find the issue with some more detail explained. Hope this gets resolved soon!

**Comment by Cristelknight** [comment]
A known problem. It is some weird mc bug I think. In the next update there will be a wwoo config option which will force mc to generate large biomes. There seems to be no other way.

**Comment by Cristelknight** [comment]
In mod version 3.1.9 a option was added to force Minecraft to generate large biomes.
