### ISSUE TITLE
[1.21.1] [neoforge] oceans are broken, corrupt chunks

### ISSUE THREAD

**Issue by eternalbluepetya** [Cristelknight/Expanded-Ecosphere#115]
so, i dont know if this mod is _entirely_ causing the issue, but [someone here reported the same issue](https://github.com/Cristelknight999/Expanded-Ecosphere/issues/101) with the same two specific mods (lithosphere + this mod) so i thought id also report an issue. i was able to play my world fine. got off for a couple days, came back on, and my chunks were starting to corrupt. it had this weird bumpy stone sponge texture with snow on it. ![2024-10-19_21 21 15](https://github.com/user-attachments/assets/4b6703fc-1202-49e0-9f4a-0b1b6b60b6fd)
i knew i added a couple cosmetic mods since the last time i played and assumed that was the issue, so i scanned through my mods, looking at their issues, seeing if anyone had reported the same one. then i made a new world and was greeted with this ocean generation.
![2024-10-19_21 32 42](https://github.com/user-attachments/assets/c715aef5-ad95-484c-a7db-e160a89a519d)
so i checked lithospheres issues, found nothing, and then found someone else had this issue with this mod and lithosphere. i don't know which one is causing the issue, im not trying to accuse this mod of anything, i just thought id report my experience. [here is my logs for the corrupting chunks, if it helps.](https://mclo.gs/LswGVN2)

**Comment by Cristelknight** [comment]
Expanded ecosphere compat with other worldgen mods isn't really a priority. I don't think this will get fixed. If you want to use other worldgen mods with WWEE use WWOO instead.

**Comment by eternalbluepetya** [comment]
okay! thank you for responding. great mod by the way, genuinely my favorite biome mod
