### ISSUE TITLE
Crash on NeoForge dedicated server load while attempting to create ClothConfigScreen

### ISSUE THREAD

**Issue by LAmTheGoose** [Cristelknight/Expanded-Ecosphere#117]
When the mod loads on NeoForge, it checks whether Cloth Config is present, and if it is, attempts to create a ClothConfigScreen regardless of whether the mod is being run on a server or a client. This causes a crash on a dedicated server with Cloth Config and WWEE installed.

**Comment by Cristelknight** [comment]
already fixed in 1.21.3

do you need a backport?

**Comment by steelsicarius** [comment]
Could it be updated for neoforge version 1.21.1?

Thank you so much
