### ISSUE TITLE
[1.19.2-Forge] `wwoo_forge.config.text.newUpdateBig` in chat

### ISSUE THREAD

**Issue by thimblebird** [Cristelknight/Expanded-Ecosphere#12]
see screenshot, after latest update to `3.1.9`

![image](https://user-images.githubusercontent.com/93487547/205385542-3b79209d-5927-46dd-8e29-e1c24435ed21.png)
[latest.log](https://github.com/Cristelknight999/WWOO/files/10144312/latest.log)

**Comment by Cristelknight** [comment]
i'll take a look at it. weird

**Comment by Cristelknight** [comment]
I can‘t reproduce it. In that screenshot you used 3.1.9? Or 3.1.8? And you used forge, or?

**Comment by thimblebird** [comment]
see latest log and first comment; screenshot taken after update from `3.1.8` to `3.1.9` and joining an existing world. and issue title (`1.19.2-Forge`)... forge `43.1.57` if that helps

**Comment by thimblebird** [comment]
every time i load up this world in Forge `43.2.0`, Minecraft `1.19.2`:
[New World (6).zip](https://github.com/Cristelknight999/WWOO/files/10252634/New.World.6.zip)
(i'm using a rather big modpack, but i hope it loads ok for you regardless)

using this version of the mod:
`WWOO-FORGE-3.1.9+1.19.x`

with this config:
[wwoo.json5.txt](https://github.com/Cristelknight999/WWOO/files/10252635/wwoo.json5.txt)

in case you still can't reproduce it

**Comment by Cristelknight** [comment]
thx for reporting this. i finally found the problem (i didn't spend much time looking after it to be honest, so it took really long).
This will be fixed in version 3.1.10 which i'll release today (for 1.19.3)
