### ISSUE TITLE
Feature Request: Plans to update to 1.21.4?

### ISSUE THREAD

**Issue by cr-gomezm** [Cristelknight/Expanded-Ecosphere#121]
Using the mod on 1.21.4 returns the followint errors:

> Errors in registry minecraft:root:
>> Errors in element minecraft:worldgen/biome:
java.lang.IllegalStateException: Unbound values in registry ResourceKey[minecraft:root / minecraft:worldgen/biome]: [wythers:andesite_crags, wythers:calcite_caverns, wythers:cool_stony_peaks, minecraft:deep_dark, wythers:deep_dark_forest, wythers:deep_dark_incursion, wythers:deep_underground, wythers:frozen_island, wythers:fungous_dripstone_caves, wythers:granite_canyon, wythers:icy_crags, wythers:lichenous_caves, wythers:lichenous_dripstone_caves, wythers:lush_dripstone_caves, wythers:lush_fungous_dripstone_caves, wythers:lush_shroom_caves, minecraft:mangrove_swamp, wythers:mossy_caves, wythers:mossy_dripstone_caves, wythers:mushroom_caves, wythers:snowy_canyon, wythers:snowy_peaks, wythers:underground, wythers:volcanic_chamber]

> Errors in registry minecraft:worldgen/biome:
>> Errors in element wythers:andesite_crags:
java.lang.IllegalStateException: Failed to parse wythers:worldgen/biome/andesite_crags.json from pack expanded_ecosphere

And so on...

Errors are expected as the mod is not listed to be compatible with 1.21.4 but the requirement in the json file is >=1.21.3

  "depends": {
    "fabricloader": ">=0.15.11",
    "fabric": "*",
    "minecraft": ">=1.21.3",
    "cristellib": ">=1.2.8"
  },
  
  Will love to see this mod updated... thanks for the hard work!!! ❤

**Comment by Cristelknight** [comment]
Yeah. Not sure if this mod will get updated to 1.21.4

The focus is more on WWOO. We'll see...

**Comment by Cristelknight** [comment]
@cr-gomezm so on the discord Server I uploaded a datapack version of WWEE 1.21.4 with no pale garden (yet)

**Comment by cr-gomezm** [comment]
How fast... thanks a lot, I took anyway a look to WWOO as you stated, not completely sure about the differences but if the future of the mod is that... we should began using it I think 😊

**Comment by Cristelknight** [comment]
Differences are: 
- WWEE more NEW biomes and more realistic layout, WWOO no new biomes, but sub-biomes and even biome transitions.
- WWEE slightly changes terrain generation, WWOO does not at all. 

=> So WWOO is way better compatible with other world-gen mods, but WWEE might be more realistic if used alone.

**Comment by vanyasem** [comment]
@Cristelknight999 Greetings! 

I noticed that there's now an `architectury-1.21.4` branch in the repo
Does that mean we'll eventually see support for 1.21.4 come out?
From what I can see, a version for 1.21.4 is not available on Modrinth/Sourceforge
If it’s not ready or not finished, could you please let me know what’s the current state of it?

Thanks a bunch!
