### ISSUE TITLE
[Mod] Incompatible with Quilt

### ISSUE THREAD

**Issue by greensad** [Cristelknight/Expanded-Ecosphere#13]
Crashes standalone.

Quilt Version 0.17.7
Minecraft Version 1.19.2
WWOO Version 3.1.9
Quilted Fabric API Version 4.0.0 beta 23

Log: https://mclo.gs/FHJGDzZ

**Comment by Cristelknight** [comment]
known

**Comment by greensad** [comment]
> known

Ah, I see. You might consider adding that to the known incompatibility list to avoid future tickets : )
