### ISSUE TITLE
[Fabric 1.19.2] Andesite, Diorite and Granite aren't generaing at all 

### ISSUE THREAD

**Issue by SatDog92** [Cristelknight/Expanded-Ecosphere#14]
I've noticed a problem with this mod, that special stones such as Andesite, Diorite and Granite aren't generated where they should in the overworld, even when custom biomes are disabled. Whether custom biomes are disabled or not, i am forced to farm these stones by using quartz or by finding biomes with these generating, which can get pretty annoying, since biomes like Savanna that generate a lot of surface granite can spawn several hundreds of blocks away.

If this not intended, here's a bug, but if this is intended to happen, it's a very bad idea, since these stone types are usually obtainable easily.

Using mod version 3.1.9

**Comment by Cristelknight** [comment]
It is intended, but it will be changed in the future, because of all those complaints.

**Comment by Optify1** [comment]
https://www.curseforge.com/minecraft/texture-packs/william-wythers-create-compat-datapack

**Comment by TimLiz** [comment]
I have the same problem, it was very disappointing when I found out that there is no andesite in my world with custom biomes disabled.

**Comment by Cristelknight** [comment]
There is a datapack, that re-adds them just above. Just use that

**Comment by Cristelknight** [comment]
I also made a option for it in the newest versionwhich will be released soon.
