### ISSUE TITLE
Incompatible to TerraBlender?

### ISSUE THREAD

**Issue by TheButterbrotMan** [Cristelknight/Expanded-Ecosphere#16]
https://bytebin.lucko.me/QR2hA8cX9S

Hello, i am experiencing this crash, while launching the game.

**Comment by Cristelknight** [comment]
This is probably not a Terrablender Issue. You can close your issue there.
Did you enable Compatible mode in WWOO? If not, idk what could cause this crash.

**Comment by TheButterbrotMan** [comment]
> 

Yes, i did enable that.

**Comment by TheButterbrotMan** [comment]
Anything i can do to help you?

**Comment by KevinTheG0D** [comment]
Did this crash happen only once?
Does WWOO work without compatible mode?
