### ISSUE TITLE
[Suggestion] Compatiblity with Shattered World Limit

### ISSUE THREAD

**Issue by ItzEnderArkail** [Cristelknight/Expanded-Ecosphere#18]
it would be awesome to see this generator being compatible with [Shattered world limit](https://www.curseforge.com/minecraft/mc-mods/new-world-height-and-depth) which increases the depth and height limit, it can reach to Y 1024 to -512

atm things don't generate properly, the mod tries to generate his own geodes but they can't

**Comment by Cristelknight** [comment]
just open the wwoo mod file and go to resources/wwoo_default/data/minecraft/worldgen/noise_settings/large_biomes.json
and change the options in the "noise" object. you don't need another mod for it

**Comment by ItzEnderArkail** [comment]
> just open the wwoo mod file and go to resources/wwoo_default/data/minecraft/worldgen/noise_settings/large_biomes.json and change the options in the "noise" object. you don't need another mod for it

by just changing "min_y" and "height" will also generate caves below -64?

**Comment by KevinTheG0D** [comment]
Yes it should. But you have to set correct values you can’t do something like min_y: -97 and height: 12
