### ISSUE TITLE
[1.18.2][FORGE] Does not have configuration files

### ISSUE THREAD

**Issue by odevjorge** [Cristelknight/Expanded-Ecosphere#20]
I couldn't find the configuration files, I already started the game and created a world, but the "config/wwoo/" folder is not being generated.

![Captura de ecrã de 2023-02-02 12-27-01](https://user-images.githubusercontent.com/89429512/216367199-a6d27817-6f73-436c-a9de-abad6ba3a8bf.png)

![Captura de ecrã de 2023-02-02 12-34-24](https://user-images.githubusercontent.com/89429512/216369072-f0346791-7e91-47e7-b418-eb4b38a29a5f.png)

**Comment by Cristelknight** [comment]
Only version 3.0 and higher has config
