### ISSUE TITLE
World Gen Overrides the Superflat Option

### ISSUE THREAD

**Issue by CasualGeorge** [Cristelknight/Expanded-Ecosphere#21]
Hey, man! First off, I love your world gen. Absolutely the best generation mod out there, imo. :D 
Anyways, it seems that opting for the "Superflat" world option results in a normally generated world.

**Comment by Cristelknight** [comment]
This is a minecraft bug that can’t be fixed easily.

**Comment by RandomGuy91** [comment]
What kind of response is that???
