### ISSUE TITLE
Latest version of wwoo for 1.19.2 breaks settings

### ISSUE THREAD

**Issue by Herobattler** [Cristelknight/Expanded-Ecosphere#23]
On the latest 1.19.2 edition of woo the save function doesn't save anything

**Comment by Cristelknight** [comment]
fabric or forge?

**Comment by Herobattler** [comment]
> fabric or forge?

Forge 1.19.2  Especifically the ingame settings dont save only the config file outside of the game saves.

**Comment by Cristelknight** [comment]
thx for reporting this. a forge version problem. i'll fix it in the 1.19.3 forge version for sure. But idk if i'll make a backport for 1.19.2

**Comment by OutrightWings** [comment]
A vast majority of mods are not moving to 1.19.3, so it would greatly benefit modpack makers-such as myself-if you did.

**Comment by sdarkwell** [comment]
**@Cristelknight999,**

I agree with @OutrightWings: In no way do I wish to trivialize the effort required to maintain multiple versions of a mod, but it does leave modpack developers in an awkward place.

I'm currently working on a modpack of my own, and have been anxiously hoping for a 1.19.2 version that allows disabling of limited underground granite/diorite/andesite generation.

Even if you never backport, thank you so much for your efforts in creating and maintaining this mod!

**Thank you and be well.** :)
- S.

**Comment by Cristelknight** [comment]
I‘ll do it. But I don’t understand why this should be important for modpacks or something else. It is just a bug which is annoying but nothing game breaking.

**Comment by ModernGamingWorld** [comment]
@Cristelknight999 I am also having this on 1.19.2 and need this fixed as it's not saving after I change it to COMPATIBLE
