### ISSUE TITLE
1.19.2 Fabric-3.1.9.1(Crash on world gen)

### ISSUE THREAD

**Issue by ghost** [Cristelknight/Expanded-Ecosphere#25]
I added this to my mod set-up, and I started a new test world it crashed. The mod set-up worked with no issues before adding WWOO.  A new test world loaded without issues, when I set it to update only vanilla biomes. But, just loading a new world without making that change causes a crash each time. 

---- Minecraft Crash Report ----
// You're mean.

Time: 2023-02-12 11:17:26
Description: Exception generating new chunk

java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / wythers:bamboo_swamp]=net.minecraft.class_1959@75c71ceb}]
	at net.minecraft.class_7510.method_44210(class_7510.java:100)
	at net.minecraft.class_2794.mdd92414$lambda$updateFeaturesPerStep$1$0(class_2794.java:2854)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at net.minecraft.class_2794.method_12102(class_2794.java:397)
	at net.minecraft.class_2806.method_20613(class_2806.java:145)
	at net.minecraft.class_2806.method_12154(class_2806.java:292)
	at net.minecraft.class_3898.method_17225(class_3898.java:679)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:673)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:62)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_7510.method_44210(class_7510.java:100)
	at net.minecraft.class_2794.mdd92414$lambda$updateFeaturesPerStep$1$0(class_2794.java:2854)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at net.minecraft.class_2794.method_12102(class_2794.java:397)
	at net.minecraft.class_2806.method_20613(class_2806.java:145)
	at net.minecraft.class_2806.method_12154(class_2806.java:292)
	at net.minecraft.class_3898.method_17225(class_3898.java:679)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:673)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:62)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)

-- Chunk to be generated --
Details:
	Location: 1,27
	Position hash: 115964116993
	Generator: net.minecraft.class_3754@4633188b
Stacktrace:
	at net.minecraft.class_3898.method_17225(class_3898.java:679)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:673)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:62)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 625
	Level dimension: minecraft:overworld
	Level spawn location: World: (40,64,456), Section: (at 8,0,8 in 2,4,28; chunk contains blocks 32,-64,448 to 47,319,463), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 0 game time, 0 day time
	Level name: New Mods Test2
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:367)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:315)
	at net.minecraft.class_1132.method_3823(class_1132.java:68)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2416163448 bytes (2304 MiB) / 5368709120 bytes (5120 MiB) up to 5368709120 bytes (5120 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 4600H with Radeon Graphics         
	Identifier: AuthenticAMD Family 23 Model 96 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.99
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: 0x1636
	Graphics card #0 versionInfo: DriverVersion=27.20.11032.9001
	Graphics card #1 name: NVIDIA GeForce GTX 1650 Ti
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1f95
	Graphics card #1 versionInfo: DriverVersion=31.0.15.1640
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 30913.80
	Virtual memory used (MB): 15328.04
	Swap memory total (MB): 23314.45
	Swap memory used (MB): 1884.52
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		additionaladditions: Additional Additions 5.1.0
			libgui: LibGui 6.0.0-beta.5+1.19-pre1
				jankson: Jankson 4.1.1+j1.2.1
				libninepatch: LibNinePatch 1.1.0
		adorn: Adorn 3.7.0+1.19.2
		ambientsounds: Ambient Sounds (Fabric) 5.2.13
		appleskin: AppleSkin 2.4.1+mc1.19
		architectury: Architectury 6.2.46
		axolotlitemfix: Axolotl Item Fix 1.1.4
		balm-fabric: Balm 4.5.2+0
		bcc: BetterCompatibilityChecker 2.0.2-build.16+mc1.19.1
		bedspreads: Bedspreads 6.0.0+1.19.2
		betteradvancements: Better Advancements 0.2.2.142
		bettermineshafts: YUNG's Better Mineshafts 1.19.2-Fabric-3.2.0
		betterstats: Better Statistics Screen 2.1.1+1.19.2
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
		bookshelf: Bookshelf 16.2.16
		bountiful: Bountiful 3.0.0
		brewinandchewin: Brewin And Chewin fabric-1.0.5+1.19.2
		byg: Oh The Biomes You'll Go 2.0.0.13
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		carrier: Carrier 1.11.0
		chalk: Chalk 2.1.0+1.19
		charm: Charm 4.4.4
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cloth-api: Cloth API 4.0.65
			cloth-basic-math: cloth-basic-math 0.6.1
			cloth-client-events-v0: Cloth Client Events v0 4.0.65
			cloth-common-events-v1: Cloth Common Events v1 4.0.65
			cloth-scissors-api-v1: Cloth Scissors API v1 4.0.65
			cloth-utils-v1: Cloth Utils v1 4.0.65
		cloth-config: Cloth Config v8 8.2.88
		comforts: Comforts 6.0.2+1.19.2
		continuity: Continuity 2.0.1+1.19
		create: Create 0.5.0g-796+1.19.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			fake-player-api: Fake Player API 0.5.0
			flywheel: Flywheel 0.6.8-1
			milk: Milk Lib 1.0.51
				dripstone_fluid_lib: Dripstone Fluid Lib 2.0.1
			noindium: No Indium? 1.1.0+1.19
			porting_lib: Porting Lib 2.1.623+1.19.2
				forge_tags: Porting Lib Tags 3.0
				porting_lib_base: Porting Lib Base 2.1.623+1.19.2
					com_github_llamalad7_mixinextras: MixinExtras 0.1.1
					serialization_hooks: Serialization Hooks 0.3.26
				porting_lib_entity: Porting Lib Entity 2.1.623+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.623+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.623+1.19.2
				porting_lib_models: Porting Lib Models 2.1.623+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.623+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.623+1.19.2
					porting_lib_model_loader: Porting Lib Model Loader 2.1.623+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.623+1.19.2
					porting_lib_extensions: Porting Lib Extensions 2.1.623+1.19.2
						porting_lib_accessors: Porting Lib Accessors 2.1.623+1.19.2
						porting_lib_attributes: Porting Lib Attributes 2.1.623+1.19.2
							porting_lib_constants: Porting Lib Constants 2.1.623+1.19.2
						porting_lib_common: Porting Lib Common 2.1.623+1.19.2
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			registrate-fabric: Registrate for Fabric 1.1.44-MC1.19.2
		creativecore: CreativeCore (Fabric) 2.9.3
		cullleaves: Cull Leaves 3.0.1
			midnightlib: MidnightLib 1.0.0
		culturaldelights: Cultural Delights Fabric 0.14.9+1.19.2
			terraform-wood-api-v1: Terraform Wood API (v1) 4.2.0
		dashloader: DashLoader 4.1.3+1.19
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_quantumfusion_hyphen: Hyphen 0.2.2
			dev_quantumfusion_taski: Taski 1.1.0
		dawn: Dawn API 3.5.0
		decorative_blocks: Decorative Blocks 3.0.0
		dsurround: Dynamic Surroundings: Remastered Fabric Edition 0.1.0
			org_openjdk_nashorn_nashorn-core: nashorn-core 15.3
		duckling: Duckling 2.0.8
		ecologics: Ecologics 2.1.11
		ellemes_container_lib: Ellemes' Container Library 2.0.1
		enchdesc: EnchantmentDescriptions 13.0.14
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		everycomp: Every Compat 1.19.2-2.2.2
		expandeddelight: Expanded Delight 0.2.2
		expandedstorage: Expanded Storage 8.0.1
		extrasounds: ExtraSounds 2.3.1+1.19.2-1.19.1
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			soundcategories: Sound Categories 1.2.4+1.19
		fabric-api: Fabric API 0.72.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.14+6e0787e690
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.13+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.0+82db024a90
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.23+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.4+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.15+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.0+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.32+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.40+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.0+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.1+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.6+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.34+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.3+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.33+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.33+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.3+9785ec3590
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.37+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.3+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.11+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.14+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.6+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.22+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.20+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.10+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.27+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.5+9785ec3590
			fabric-particles-v1: Fabric Particles (v1) 1.0.13+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.0+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.31+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.0+2e5408b590
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.7.0+2e5408b590
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.23+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.18+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.10+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.26+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.0+08b73de490
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.3+251d254a90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.31+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.6+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.23+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.5+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.8.4+kotlin.1.7.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.3
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.0
		fabricloader: Fabric Loader 0.14.11
		fabrishot: Fabrishot 1.9.1
		fallingtree: FallingTree 3.10.0
		farmersdelight: Farmer's Delight 1.19.2-1.3.9
		ferritecore: FerriteCore 5.0.3
		forgeconfigapiport: Forge Config API Port 4.2.10
		frame: Frame 0.26.1+1.19-fabric
			frame-api-base: Frame Base 0.2.1+906ebc04a9
			frame-blocks-v0: Frame Blocks (v0) 0.1.3+233e7428a9
			frame-config-v0: Frame Config (v0) 0.3.1+0fa45150a9
			frame-content-registries-v0: Frame Content Registries (v0) 0.4.0+2876b511a9
			frame-enchantments-v0: Frame Enchantments (v0) 0.1.0+4093105da9
				mm: Manningham Mills 2.3
			frame-game-rules-v0: Frame Game Rules (v0) 0.2.4+e7ce56a6a9
			frame-items-v0: Frame Items (v0) 0.1.3+906ebc04a9
			frame-loot-tables-v0: Frame Loot Tables (v0) 0.1.4+4f7341eca9
			frame-registries-v0: Frame Registries (v0) 0.1.1+0e0ec74ea9
			frame-rendering-v0: Frame Rendering (v0) 0.1.5+906ebc04a9
			frame-tabbed-item-groups-v0: Frame Tabbed Item Groups (v0) 0.2.4+0aca9b56a9
			frame-toymaker-v0: Frame Data Generation Helpers (v0) 0.6.1+b13741c3a9
			frame-woods-v0: Frame Woods (v0) 0.2.1+6a33fbada9
		fwaystones: Fabric Waystones 3.0.5+mc1.19.2
		geckolib3: Geckolib 3.1.38
			com_eliotlash_mclib_mclib: mclib 20
		geophilic-fabric: Geophilic 1.19-1.0.1
		go-fish: Go Fish 1.6.0-1.19.1
		goblintraders: Goblin Traders 1.5.2
		goodall: Goodall 1.2.0
		guardvillagers: Guard Villagers Fabric 1.19.2-1.0.16
		highlighter: Highlighter 1.1.4
		iceberg: Iceberg 1.0.46
		indium: Indium 1.0.9+mc1.19.2
		inmis: Inmis 2.7.1-1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		inmisaddon: InmisAddon 1.0.3
		interactic: Interactic 0.1.11+1.19
		inventoryessentials: Inventory Essentials 5.0.0
		inventoryhud: Inventory HUD + 3.4.7
		iris: Iris 1.5.0
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre8
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		jade: Jade 8.7.3
		jamlib: JamLib 0.6.0+1.19.3
		java: OpenJDK 64-Bit Server VM 17
		kambrik: Kambrik 4.0-1.19.2
		kleeslabs: KleeSlabs 12.1.0
		lapisreserve: Lapis Reserve 1.0.8
		lazydfu: LazyDFU 0.1.3
		lootintegrations: Loot integration Mod 1.19.1-1.7
		magnumtorch: Magnum Torch 4.2.0
		mavapi: More Axolotl Variants API 1.0.1
		mavm: More Axolotl Variants Mod 1.1.0
		mcwbridges: Macaw's Bridges 1.0.6
		mcwroofs: Macaw's Roofs 2.2.2
		memoryleakfix: memory Leak Fix 1.19.1-0.7.0
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.1.2
		moonlight: Moonlight 1.19.2-2.1.27
		mvs: Vanilla Structure Mod 2.5.10-1.19.2
		naturalist: Naturalist 2.1.1
		naturescompass: Nature's Compass 1.19.2-2.1.0-fabric
		netherportalfix: NetherPortalFix 10.0.0
		owo: oωo 0.8.2+1.19
			blue_endless_jankson: jankson 1.2.1
		patchouli: Patchouli 1.19.2-76-FABRIC
			fiber: fiber 0.23.0-2
		plushies: Plushie Mod 1.2
		polymorph: Polymorph 0.46.1+1.19.2
			cardinal-components-item: Cardinal Components API (items) 5.0.1
			spectrelib: SpectreLib 0.11.0+1.19
		presencefootsteps: Presence Footsteps 1.6.2
			kirin: Kirin UI 1.11.1
		puzzleslib: Puzzles Lib 4.3.12
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		repurposed_structures: Repurposed Structures 6.1.3+1.19.2
		rightclickharvest: Right Click Harvest 3.1.0+1.19-1.19.2
		roughlyenoughitems: Roughly Enough Items 9.1.550
			error_notifier: Error Notifier 1.0.9
		roughlyenoughprofessions: Roughly Enough Professions 1.1.3
		smarterfarmers: Smarter Farmers 1.19.2-1.7.0
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		spiceoffabric: Spice of Fabric 1.6.0-beta.2+1.19.2
			coat: Coat 1.0.0-beta.18+mc22w17a
			tweed4_annotated: tweed4_annotated 1.3.1+mc22w17a
			tweed4_base: tweed4_base 1.7.1+mc22w17a
			tweed4_data: tweed4_data 1.2.1+mc22w17a
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc22w17a
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc22w17a
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.1+mc22w17a
		spoornarmorattributes: SpoornArmorAttributes 2.0.6-1.19
			net_objecthunter_exp4j: exp4j 0.4.8
		spoornweaponattributes: SpoornWeaponAttributes 4.0.9-1.19
		supplementaries: Supplementaries 1.19.2-2.2.35
		tcdcommons: TCD Commons API 1.1+1.19.2
		terrablender: TerraBlender 2.0.1.127
		thonkutil: ThonkUtil 2.15.4+1.19
			thonkutil-base: ThonkUtil Base 1.13.2+4a8c408a57
			thonkutil-capes-v1: ThonkUtil Capes (v1) 1.4.2+3eb2749857
			thonkutil-coords-v1: ThonkUtil Coords (v1) 1.1.2+8ff533c957
			thonkutil-customization-v1: ThonkUtil Customization (v1) 1.1.2+8ff533c957
			thonkutil-legacy: ThonkUtil Legacy 1.1.2+5d4263f557
			thonkutil-modchecker-v1: ThonkUtil ModChecker (v1) 1.1.3+bd4b387957
			thonkutil-potions-v0: ThonkUtil Potions (v0) 1.5.2+8ff533c957
			thonkutil-titlescreen-v1: ThonkUtil TitleScreen (v1) 1.2.2+8ff533c957
			thonkutil-trades-v1: ThonkUtil Trades (v1) 1.2.2+8ff533c957
		tradingpost: Trading Post 4.2.0
		trinkets: Trinkets 3.4.1
		twigs: Twigs 2.0.0-beta.9+1.19-fabric
		universal_ores: Universal Ores 1.4.2
		variantcraftingtables: Variant Crafting Tables 3.2.9
		villagernames: Villager Names 4.0.8
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
		vinery: Vinery 1.1.4
		windchimes: Windchimes 1.2.1
		wwoo: William Wythers' Overhauled Overworld 3.1.9.1
		xaerominimap: Xaero's Minimap 22.17.1
		xaeroworldmap: Xaero's World Map 1.28.8
		xp_storage: XP Storage 1.4.3+1.19
		yigd: You're in Grave Danger 1.4.4
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.2
			org_javassist_javassist: javassist 3.28.0-GA
			org_reflections_reflections: reflections 0.10.2
		yungsextras: YUNG's Extras 1.19.2-Fabric-3.1.0
	Loaded Shaderpack: ComplementaryShaders_v4.6.zip
		Profile: HIGH (+3 options changed by user)
	NEC status: No NEC detected
	Flywheel Backend: Off
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, Fabric Mods, WWOO, Everycomp Generated Pack, Supplementaries Generated Pack
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.14.11-1.19.2

**Comment by Cristelknight** [comment]
Which mods do you have that add biomes?

**Comment by KuroNeko87** [comment]
I see you have geophilic installed, it generates biomes and needs terrablender

Install Cyanide https://www.curseforge.com/minecraft/mc-mods/cyanide-fabric and it will tell you what feature is giving you issues.

**Comment by dmkenza** [comment]
@KuroNeko87 
I have an error with BYG

Caused by: com.alcatrazescapee.cyanide.codec.FeatureCycleDetector$FeatureCycleException: A feature cycle was found.

Cycle:
At step 9
Feature 'minecraft:patch_grass_savanna'
  must be before 'minecraft:patch_grass_taiga_2' (defined in 'byg:maple_taiga' at index 2, 3)
  must be before 'minecraft:brown_mushroom_taiga' (defined in 'byg:shattered_glacier' at index 3, 4 and 8 others)
  must be before 'minecraft:red_mushroom_taiga' (defined in 'minecraft:mushroom_fields' at index 2, 3 and 14 others)
  must be before 'minecraft:patch_grass_savanna' (defined in 'wythers:cold_island' at index 4, 5)

	at com.alcatrazescapee.cyanide.codec.FeatureCycleDetector.buildFeaturesPerStep(FeatureCycleDetector.java:141)
	at net.minecraft.class_7510.handler$bmf000$buildFeaturesPerStepWithAdvancedCycleDetection(class_7510.java:529)
	at net.minecraft.class_7510.method_44210(class_7510.java)
	at net.minecraft.class_2794.method_44215(class_2794.java:136)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at net.minecraft.class_2794.method_12102(class_2794.java:397)
	at net.minecraft.class_2806.method_20613(class_2806.java:145)
	at net.minecraft.class_2806.method_12154(class_2806.java:292)
	at net.minecraft.class_3898.method_17225(class_3898.java:679)
	... 14 more

**Comment by dmkenza** [comment]
Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.1.0
causes the problem for now.

Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.0.7
The previous one dosnt cause.

**Comment by Cristelknight** [comment]
Thx for reporting this. Just use the older byg version until it is fixed.
