### ISSUE TITLE
[Fabric/1.19.2] Structure Command keeps gamecrashing

### ISSUE THREAD

**Issue by SgtKaneki** [Cristelknight/Expanded-Ecosphere#26]
If I use "/locate structure wythers:el_dorado" the game keeps freezing and crashing after a 30-60 Seconds.
Other wythers-structers commands keep working as I tested.

I am using Fabric, 1.19.2, Terralith, TerraBlender and WWOO with compatibility mode.

**Comment by Cristelknight** [comment]
This is because it is just a really really really rare „structure“. So mc can’t find it.
