### ISSUE TITLE
Crash upon attempting to generate chunk

### ISSUE THREAD

**Issue by Gutter-Slug** [Cristelknight/Expanded-Ecosphere#28]
I'm in 1.19.2 and discovered a chunk that can't generate. The crash log lists it as "bamboo_swamp" which is the same biome another user had when their world crashed. Luckily I have the world backed up before encountering the chunk so I've been attempting to find the right combination of updates/ mods that works. No luck so far 
[crash-2023-03-13_20.05.37-server.txt](https://github.com/Cristelknight999/WWOO/files/10963559/crash-2023-03-13_20.05.37-server.txt)

**Comment by GoddessStorm** [comment]
I had a similar issue and found out that its an incompatibility with cultural delight's through the cyanide mod, when I disabled the mod and the issue stopped occurring.

**Comment by Cristelknight** [comment]
install cyanide, and check what the crash log says then. then you should know, what the problem is.

**Comment by Tempest-5ky** [comment]
Hello! I've been experiencing a server crash from this issue, and I can provide a crashlog for it. Is this an issue on their (Cultural Delights') end, or yours?
https://mclo.gs/3Wdy0dB
(the mod: https://www.curseforge.com/minecraft/mc-mods/cultural-delights-fabric )
