### ISSUE TITLE
1.18.2 Fabric - Nether is changed and flat now

### ISSUE THREAD

**Issue by LLytho** [Cristelknight/Expanded-Ecosphere#3]
Hey,

with a clean fabric installation and only WWOO installed, the nether is also changed. The roof is flat and the ground is basically flat too but with a bit elevation. 

![image](https://user-images.githubusercontent.com/29131229/199585313-5c0a4fdc-361d-4d92-8ed4-f8da20c50c97.png)

**Comment by Cristelknight** [comment]
That really doesn’t look like a wwoo bug, because it doesn’t touch other dimensions then the overworld. And 1.18.2 isn’t really supported anymore. But I’ll take a look at it tomorrow.

**Comment by Optify1** [comment]
I've had the same issue on forge 1.18.2. The Nether generates with overworld-like terrain, no lava oceans, etc. Only this mod is installed.

**Comment by Optify1** [comment]
Installing amplified nether seems to fix the problem.
