### ISSUE TITLE
I can confirm this does not work on Quilt.

### ISSUE THREAD

**Issue by Sunconure11** [Cristelknight/Expanded-Ecosphere#30]
https://pastebin.com/nCXrqYkQ

Given the differences between the two aren't that huge, it shouldn't be that hard to make a port. @Cristelknight999

**Comment by k2helix** [comment]
Can confirm this also happens on 1.19.4
Same log

**Comment by Cristelknight** [comment]
Yes. This mod doesn’t support quilt. If you don’t need the config, use the datapack version, until I’ll make a quilt version someday

**Comment by Abbie5** [comment]
hi, please stop mixing into fabric internals, fabric has a stable api for what you're doing. using the api will allow the mod to run on quilt, and will also prevent it from breaking on fabric api updates.

**Comment by Cristelknight** [comment]
Really? it has? please show me where

**Comment by Cristelknight** [comment]
and i don't think fabric will often change this. And i'll use cristel lib in future, which has quilt support.

**Comment by Abbie5** [comment]
it's `net.fabricmc.fabric.api.resource.ResourceManagerHelper#registerBuiltinResourcePack`

**Comment by Cristelknight** [comment]
I know it exists. But then I can't disable packs on runtime. Or can I?
