### ISSUE TITLE
Unpredictable frog colours

### ISSUE THREAD

**Issue by ndg-creative** [Cristelknight/Expanded-Ecosphere#31]
A server I’m playing on uses the overhauled overworld datapack, and we have been unable to spawn any white frogs.  The minecraft wiki indicates we should be able to spawn white frogs in warm biomes, but when we try to spawn them in any custom biomes we get orange frogs, and when we spawn them in minecraft biomes we get green (which should be cold biome spawns!)

Is this a known issue or could it be looked into?  Thanks

**Comment by Cristelknight** [comment]
We changed where the frogs spawn. here are the lists, where they spawn:

Green Frogs:
    "minecraft:warm_ocean",
    "#minecraft:is_jungle",
    "minecraft:mangrove_swamp",
    "wythers:bayou",
    "wythers:dripleaf_swamp",
    "wythers:ancient_emerald_beech_forest",
    "wythers:ancient_moss_forest",
    "wythers:jade_highlands",
    "wythers:ancient_mossy_swamp"
    
White Frogs:
    "minecraft:snowy_plains",
    "minecraft:ice_spikes",
    "minecraft:frozen_peaks",
    "minecraft:jagged_peaks",
    "minecraft:snowy_slopes",
    "minecraft:frozen_ocean",
    "minecraft:deep_frozen_ocean",
    "minecraft:grove",
    "minecraft:deep_dark",
    "minecraft:frozen_river",
    "minecraft:snowy_taiga",
    "minecraft:snowy_beach",
    "#minecraft:is_end",
    "minecraft:desert",
    "minecraft:dark_forest",
    "wythers:forbidden_forest",
    "wythers:ancient_oak_swamp",
    "wythers:birch_swamp",
    "wythers:snowy_thermal_taiga",
    "wythers:deep_snowy_taiga",
    "wythers:icy_crags"
    
The "normal" frog spawns in the rest of the biomes
