### ISSUE TITLE
Texture pack download

### ISSUE THREAD

**Issue by ghost** [Cristelknight/Expanded-Ecosphere#32]
When using the mod I noticed some of the textures look different. Like here where you can see the trees look red:
![image](https://user-images.githubusercontent.com/81658610/231448589-2ffe16f6-8d59-4d55-8bb7-f2ac3a2d0073.png)

I was wondering if I can have a download of this texture pack because it doesn't seem to work on my server. It doesn't look 100% right without the textures. Can I have the download? Thanks.

**Comment by Cristelknight** [comment]
There is no texture pack. WWOO only uses vanilla textures. So it’s completely normal
