### ISSUE TITLE
[1.19.4/FABRIC] tangled forests are infested with thousands of pufferfish.

### ISSUE THREAD

**Issue by jabthetab** [Cristelknight/Expanded-Ecosphere#34]
i think i've figured out a possible cause. the spawn settings for the tangled forest biome has pufferfish in water_creatures instead of water_ambient like the other biomes do.
footage below.
https://user-images.githubusercontent.com/95195478/233887741-47490f47-8a7e-4aaf-bd78-c00b9dfef88d.mp4

**Comment by Cristelknight** [comment]
I thought i fixed that. Someone else had that problem, months ago. Thx for reporting it

**Comment by jabthetab** [comment]
is there any progress on this btw? is it confirmed to be caused by the reason that i suspected?
i apologise for my ignorance if it's more complex than that, especially since i'm yet to do anything on my end other than just never visit that spot in my world until the curse of the relentless pufferfish has been lifted.

**Comment by Cristelknight** [comment]
It’s because of that what you thought. Just change it yourself please. I currently have no time updating wwoo

**Comment by jabthetab** [comment]
i already made a pull request and tested it. just needs to be merged.

**Comment by Cristelknight** [comment]
Saw it
