### ISSUE TITLE
Uninstalling causes massive errors

### ISSUE THREAD

**Issue by PsydameousSharm** [Cristelknight/Expanded-Ecosphere#35]
When I installed this on both server and client side to test it out, I decided to move on, and tried getting rid of it. However, when I next tried loading my worlds and servers, they both crashed because your mod wasn't there anymore. I did tons of progress when it was installed, and I don't have many worlds backed up, so rolling it back won't work. How do I uninstall it without it giving me massive errors?

**Comment by Cristelknight** [comment]
When you open a world once with wwoo, you can’t go back easily. You can copy your region files into a new world

**Comment by PsydameousSharm** [comment]
Can you be more specific? This is incredibly vague.

**Comment by Cristelknight** [comment]
You can delete your world, or if you want to keep it (the blocks at least), then:

Create a new world with the seed of the old one. Close the world. Then delete the region files of the new world. Then copy the region files of the old world into the new one. 

You can also do the same with the entity folder, the dimension folder etc. just don’t copy the level.dat files.
