### ISSUE TITLE
Underwater terrain made of gravel can generate at water level

### ISSUE THREAD

**Issue by LAmTheGoose** [Cristelknight/Expanded-Ecosphere#4]
When rivers and oceans are generated using gravel, the world can generate them at the same level as the water level, creating odd-looking terrain by the water's edge or as an island.

Version: 1.19.2 Fabric

![2022-11-03_14 54 11](https://user-images.githubusercontent.com/103354380/199648031-62dd1401-1180-4448-b260-a861b8089800.png)
![2022-11-03_14 55 00](https://user-images.githubusercontent.com/103354380/199648040-6759d00a-c588-4cb4-8257-8d5bd07b243a.png)

**Comment by LAmTheGoose** [comment]
Version: 1.19.2 Fabric

**Comment by Cristelknight** [comment]
That is intended and not a bug.
