### ISSUE TITLE
[1.19.4/FABRIC] Game crashing on new fabric api versions

### ISSUE THREAD

**Issue by nanokulonq** [Cristelknight/Expanded-Ecosphere#40]
Game crashing only on Fabric API version higher 0.79.0
Crash report - https://gist.github.com/nanokulonq/196cd1efc55b143754f02fdcbb05ce31
Logs - https://gist.github.com/nanokulonq/680cf0cbfbe7dce03738805a3ea82684

**Comment by Shadowpudding** [comment]
I have the same issue. My crach report is almost the same, so i won't add it right now. I love what this mod does, so I hope this issue gets fixed soon

**Comment by Daelyx** [comment]
Same issue here, crash report almost identical, I crash when I try to play on a world or create a new one

**Comment by acwesty** [comment]
This is happening to me too! Everything is downloaded properly (such as the optional Cloth Config and TerraBlender). It crashes whenever I try to create a new world.

**Comment by RobertasJ** [comment]
seems like this change on the fabric api is the cause of the issue https://github.com/FabricMC/fabric/commit/f7923f6d3dc8cb27fb9346ee5a86a7f0728d28f4#diff-abb5e49de03dd72c0540388d57e30fcb1bbb255800703e9e69ce9e1e97aff21c

**Comment by Cristelknight** [comment]
Known problem. I'm on vacation, that's why it isn't fixed yet.

**Comment by RobertasJ** [comment]
Yeah i saw you were busy, take your time man. Hope you enjoy your vacation!

**Comment by Cristelknight** [comment]
I probably won't make a fix for it, because 1.20 is now prioritized. But if someone really needs it, I'll maybe make a backport. But you can just use older fAPI versions so idk
