### ISSUE TITLE
Honey blocks generate in trees in the tropical forest biome

### ISSUE THREAD

**Issue by Alchemicdumbass** [Cristelknight/Expanded-Ecosphere#41]
I'm not sure if this is intentional but its very strange and could be a bug. I made a new world and spawned in the tropical forest biome, and there are honey blocks on the underside of the leaves every few trees.
https://imgur.com/a/7iD1llI here is a screenshot of one I saw while walking.

**Comment by Cristelknight** [comment]
It is intended. Not a bug
