### ISSUE TITLE
World Corruptions on Forge 1.19.4 after removing mod

### ISSUE THREAD

**Issue by SilLemonBoy** [Cristelknight/Expanded-Ecosphere#43]
After the release of 1.20, I attempted to upgrade my 1.19.4 modded world to 1.20 without this mod installed until a compatible version is released, but I am always greeted with the error, "Errors in currently selected data packs prevented the world from loading. try to load in safe mode" If I try to use Safe Mode to load the world, I get "This world contains invalid or corrupted save data." This happens to every world I had used with the mod active.

I'm currently using version 3.1.13 of the mod for Forge-1.19.4-45.1.0

Is there anyway I can manually remove the mods data from my worlds folder to prevent this from happening while loading vanilla Minecraft?

**Comment by MarioSMB** [comment]
This unfortunately tends to be the case - a world won't load again without its world generation mods installed.  

There are ways to work around it that involve manually editing the level.dat file, you should have some luck looking that process up if this still concerns you.

**Comment by Cristelknight** [comment]
This is a vanilla "feature". That's also why you get a warning when loading a world with this mod. There really is no way to change that.
