### ISSUE TITLE
banned_biomes.json5 not showing

### ISSUE THREAD

**Issue by ThomasKunn** [Cristelknight/Expanded-Ecosphere#44]
As the title says, the **banned_biomes.json5** isn't showing up in **.minecraft/config/wwoo/**. Multiple restarts didn't help so I'm putting it here.

**Comment by EnderGirl1500** [comment]
I didn't even got the wwoo folder haha

**Comment by Cristelknight** [comment]
You're probably in a version without a config.

**Comment by Cristelknight** [comment]
And which version do you use ThomasKunn?
