### ISSUE TITLE
Crash/Error while create/loading world

### ISSUE THREAD

**Issue by xd4rkzghost01** [Cristelknight/Expanded-Ecosphere#5]
Hi there ! 1st of all, i love this mod and all what it bring. I just encounter an issue: when Global Game Rule mod is install. It cause the game to not load or create a new/old world and this start happend like 2-3 day ago. 

There the crash log:
[crash-2022-11-06_17.28.24-client.txt](https://github.com/Cristelknight999/WWOO/files/9946983/crash-2022-11-06_17.28.24-client.txt)

There the log files:
[2022-11-06-7.log](https://github.com/Cristelknight999/WWOO/files/9946991/2022-11-06-7.log)

My solution was to delete GlobalGameRule but i'd like to play with it (for the random respawn rule).

**Comment by Cristelknight** [comment]
So it crashed on startup?

**Comment by xd4rkzghost01** [comment]
Something like this. I dont think the problem its Wwoo in itself. As you can see in these logs: I load it with GlobalGameRules and it crash. But when i've delete GGR mod it work perfectly (even with 170+ mods)
(My bad ive  post this with my phone and click the wrong button)
