### ISSUE TITLE
[1.19.2 : Forge] Switched flower and tree features for meadow

### ISSUE THREAD

**Issue by SiverDX** [Cristelknight/Expanded-Ecosphere#50]
If custom biomes use the vanilla feature placement methods they will crash (feature cycle) with this worldgen because you switched the flower and tree placement for the meadow biome

Could you consider switching them back?

https://github.com/Cristelknight999/WWOO/blob/d4abaf68d6c62a443b53cc3af06b60a236bcd851/src/main/resources/data/minecraft/worldgen/biome/meadow.json#L88-L89

![image](https://github.com/Cristelknight999/WWOO/assets/22003703/32af0a10-6620-41be-95b1-c77e3786f0fe)

**Comment by Cristelknight** [comment]
Sure. I'm currently working on updating/reworking some parts of the mod. I will definitely also fix the feature order cycle errors

**Comment by Cristelknight** [comment]
I have a fix almost ready for upload. 2 months later...
And only 1.20.1 of course 😂
