### ISSUE TITLE
WWOO is crashing Minecraft on world creation.

### ISSUE THREAD

**Issue by Donastria** [Cristelknight/Expanded-Ecosphere#52]
Hi so I use WWOO and when I load I crash. here is the crash report. Was told by the lovely people at Fabric that it has to do with the swamp. wythers:bamboo_swamp
[crash-2023-07-31_23.01.58-server.txt](https://github.com/Cristelknight999/WWOO/files/12227040/crash-2023-07-31_23.01.58-server.txt)

https://mclo.gs/D3MENV6

**Comment by Wrathfulmaratuss** [comment]
Having the exact same issue, I hope it's fixed soon.

**Comment by Cristelknight** [comment]
You can install cyanide for a more detailed crash log, which will probably show the incompatible mod. When I'm back from vacation I will probably fix it.
