### ISSUE TITLE
[1.20.1 Forge] Config filed not generating

### ISSUE THREAD

**Issue by morelandjo** [Cristelknight/Expanded-Ecosphere#56]
Config files aren't generating in this mod when the game starts up. No config/wwoo folder is created. I've tried both beta and beta2, it's not generating config files in either version.

**Comment by Cristelknight** [comment]
They have no config yet (As mentioned in the changelog of the first beta). But there is a preview version on the dc here: https://discord.com/channels/779938168573132801/868069507053285407/1139292804607115294
