### ISSUE TITLE
[Crash] with Regions Unexplored - Fabric 1.20.1

### ISSUE THREAD

**Issue by xR4YM0ND** [Cristelknight/Expanded-Ecosphere#57]
So i have both mods WWOO & Regions Unexplored and i get a crash.
One of the Creators of RU told me it might be a WWOO issue so i post it here.

Normal Latest.Log: https://gist.github.com/xR4YM0ND/be0565b99358aaeb4cee14530414b541
Normal Crash Report: https://gist.github.com/xR4YM0ND/6759537ef35e4af473b0898076592cd8
Cyanide Crash Report: https://gist.github.com/xR4YM0ND/8e21a8fbf6d2a5a239c0cf3761f7f0b5

**Comment by KirboSoftware** [comment]
So, the feature in question that errors is the `"minecraft:patch_melon"`. In both vanilla (jungle biome) and regions (sparse rainforest biome) the features are ordered like this 
```json
"minecraft:vines",
"minecraft:patch_melon"
```
but in WWOO's bamboo jungle highlands it's:
```json
"minecraft:patch_melon",
"minecraft:vines"
```
so that should clear some things up :+1:

**Comment by Cristelknight** [comment]
Im actually already working on that fix. The version just isn't completely ready for upload yet. I also talked with the RU creator a bit.

**Comment by Cristelknight** [comment]
Almost done. There will only be a 1.20.1 upload, so I hope you're are playing on that version. Else I could probably send you wwoo as a datapack with the fix.

**Comment by xR4YM0ND** [comment]
Yes, our Modpack Aged will be updated to that version.

**Comment by Cristelknight** [comment]
I uploaded the new version so it should be fixed now
