### ISSUE TITLE
Update from 3.2.0 to 3.2.1 crash server

### ISSUE THREAD

**Issue by bloodyraoul** [Cristelknight/Expanded-Ecosphere#60]
Hello, i am running a modpack on a server with William Wythers' Overhauled Overworld mod
It's running in 1.20.1, forge 47.1.47
When I try to upgrade your mod to 3.2.1 version (and Cristel Lib to 1.1.3 version) the server doesnt start anymore with this crash and the server continue to crash even if I downgrade the versions after the first crash. I need to restore a backup
Here is the crash log, hope you can help

[crash-2023-09-14_20.20.05-server.txt](https://github.com/Cristelknight999/WWOO/files/12617128/crash-2023-09-14_20.20.05-server.txt)

**Comment by Cristelknight** [comment]
i hope this is resolved. couldn't really reproduce and the log is gone now too. If this happens again re-open it
