### ISSUE TITLE
Wool block generating in the tropical rainforest trees

### ISSUE THREAD

**Issue by RMEngelbrecht** [Cristelknight/Expanded-Ecosphere#63]
Title speaks for itself, screenshot provided.

Version 3.2.1 on fabric 1.20.1
![2023-10-10_22 16 02](https://github.com/Cristelknight999/Expanded-Ecosphere/assets/5603056/7ef210b1-4d43-4d05-af95-a57ba7130efc)

**Comment by Cristelknight** [comment]
This is intended. It's meant to be cotton I think.
