### ISSUE TITLE
[1.20.1] William Wythers Expanded Ecosphere "Exception in server tick loop"

### ISSUE THREAD

**Issue by CGMejia2001** [Cristelknight/Expanded-Ecosphere#64]
Minecraft 1.20.1
Forge 47.1.3
Expanded Ecosphere FORGE-3.2.1
Embeddium 0.2.1
Oculus 1.6.9

Modlist in the crash-report, im not sure if its WWEE or Cristel Lib crashing here but they were the two mods I added to my modlist and got this crash
crash-report: https://gist.github.com/HaizUber/9e47e74bf5cffdce431b46934d7f3e08

**Comment by Cristelknight** [comment]
i think by removing all mcfunctions this should not happen again. i'll close this
