### ISSUE TITLE
[1.19.2] (3.1.9) Crash on loading windswept jungle biome

### ISSUE THREAD

**Issue by togera13** [Cristelknight/Expanded-Ecosphere#68]
[crash-2023-10-31_18.33.21-server.txt](https://github.com/Cristelknight999/Expanded-Ecosphere/files/13221847/crash-2023-10-31_18.33.21-server.txt)
[crash-2023-10-31_18.30.09-server.txt](https://github.com/Cristelknight999/Expanded-Ecosphere/files/13221848/crash-2023-10-31_18.30.09-server.txt)
[crash-2023-10-31_18.20.35-server.txt](https://github.com/Cristelknight999/Expanded-Ecosphere/files/13221849/crash-2023-10-31_18.20.35-server.txt)
[crash-2023-10-31_18.14.56-server.txt](https://github.com/Cristelknight999/Expanded-Ecosphere/files/13221850/crash-2023-10-31_18.14.56-server.txt)
Even with compatible mode on it crashed.

Also WWOO forgets if you had compatible selected in the config on reboot, so you have to turn it on again manually every time as well.

**Comment by Reshy** [comment]
Same issue, setting it to compatible doesn't fix it.

**Comment by Cristelknight** [comment]
1.19.2 is not supported anymore. so i'll just close this
