### ISSUE TITLE
Feature cycle between WWOO and Graveyard Biomes

### ISSUE THREAD

**Issue by Satrapie** [Cristelknight/Expanded-Ecosphere#7]
Hello, it seems there is an incompatibility with [The Graveyard Biomes](https://www.curseforge.com/minecraft/mc-mods/the-graveyard-biomes-forge) due to a feature cycle

Here are the log and crash files (with the cyanide mod for the readability of the crash report)
[latest.log](https://github.com/Cristelknight999/WWOO/files/10009006/latest.log) (There also multiple "Couldn't load tag" errors with wythers biomes but that doesn't seem to be the cause of the crash)
[crash-2022-11-15_04.31.56-server.txt](https://github.com/Cristelknight999/WWOO/files/10009012/crash-2022-11-15_04.31.56-server.txt)

**Comment by Cristelknight** [comment]
Tested it with wwoo 3.1.9 fabric and Graveyard Biomes 1.6. works fine.
