### ISSUE TITLE
game crashes on 1.20.1 fabric

### ISSUE THREAD

**Issue by 3dguru** [Cristelknight/Expanded-Ecosphere#72]
When loading minecraft it crashes before the loading screen providing error below 

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'expanded_ecosphere'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class cristelknight.wwoo.ExpandedEcosphere
		at cristelknight.wwoo.fabric.terrablender.TerrablenderFabricInit.onTerraBlenderInitialized(TerrablenderFabricInit.java:11)
		at terrablender.core.TerraBlenderFabric.lambda$onInitialize$0(TerraBlenderFabric.java:40)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
		at terrablender.core.TerraBlenderFabric.onInitialize(TerraBlenderFabric.java:38)
		at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383)
		... 6 more
Caused by: java.lang.NoClassDefFoundError: net/cristellib/ModLoadingUtil
	at cristelknight.wwoo.ExpandedEcosphere.isTerraBlenderLoaded(ExpandedEcosphere.java:46)
	at cristelknight.wwoo.utils.Util.getMode(Util.java:40)
	at cristelknight.wwoo.ExpandedEcosphere.<clinit>(ExpandedEcosphere.java:20)
	at cristelknight.wwoo.fabric.ExpandedEcosphereFabric.onInitialize(ExpandedEcosphereFabric.java:10)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383)
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.cristellib.ModLoadingUtil
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 11 more

**Comment by Cristelknight** [comment]
Please send you modlist

**Comment by 3dguru** [comment]
BetterEnd
Regions Unexplored
Invocations (Spell Engine)
Forge Config API Port
More Totems of Undying
Balm (Fabric Edition)
Visual Workbench
YUNG's API
You Shall Not Spawn! [Forge/Fabric]
CleanView (Fabric)
Highlight
Villager Names
[EMF] Entity Model Features
Mindful Darkness
Cardinal Components API
AutoTag
Unsafe World Random Access Detector
Cultural Delights [Fabric]
NetherPortalFix (Fabric Edition)
Grass Overhaul (Sod)
Croptopia
Aquamirae (Fabric)
[Let's Do] Vinery
ChoiceTheorem's Overhauled Village
Pick Up Notifier
When Dungeons Arise - Fabric!
Server Performance - Smooth Chunk Save[Forge/Fabric]
MixinTrace
RightClickHarvest
No See, No Tick
Vein Mining
Zoomify
Diagonal Fences
Let's Do: API
Axolotl Bucket Fix
bad packets
Better Compatibility Checker
The Bumblezone - Quilt/Fabric
Better Advancements
Block Swap
Practical Plushies: Mobs
Basket
Dungeons and Taverns
Artifacts
Creeper Overhaul
Carry On
Complementary Shaders - Reimagined
Structure Essentials[Forge/Fabric]
Dark Enchanting
Boat Break Fix [Neo/Forge/Fabric/Quilt]
Cupboard
Keybind Fix
Cristel Lib
Konkrete
Projectile Damage Attribute
Legendary Tooltips
YUNG's Better Strongholds
Not Enough Animations
Redirector [Modern]
Item Filters
Supplementaries
Bosses of Mass Destruction
MVS - Moog's Voyager Structures
Prism
Philips Ruins
Block Runner
Fabric Seasons: Delight Compat
Bookshelf
More Axolotl Variants Mod
Jade ðŸ”
Repurposed Structures - Friends and Foes Compat
Beacon Overhaul
playerAnimator
BCLib
Trading Post
Variant Bookshelves [Fabric/Quilt]
AzureLib
Collective
Rare Ice
Patchouli
Frostiful
CraterLib
Fabric Seasons: Croptopia Compat
Shield Overhaul [Fabric/Forge]
Marium's Soulslike Weaponry
Polymorph
Auudio
DEUF Refabricated
Fabric Language Kotlin
Traveler's Backpack
Nether Chested
Iron Chests: Restocked
Create Crafts & Additions
fix GPU memory leak[Forge/Fabric]
Build Guide
Applied Energistics 2
BetterTrims
Mutant Monsters
JamLib
Dawn API
Practical Plushies: Animals
Archers (RPG Series)
MES - Moog's End Structures
Comforts
StackDeobfuscator
Oxidized
Starter Kit
All The Trims
Overflowing Bars
Mythic Mobs
Audio Extension for FancyMenu
Transparent
Structory
Farmer's Delight [Fabric]
Pufferfish's Skills
Windchimes
Universal Graves
Leaves Be Gone
Xaero's Minimap
The Graveyard (FABRIC)
Hellion's Sniffer+
Lithium
Falling Leaves
Geckolib
Tech Reborn
Wizards (RPG Series)
Mythic Mounts
Disable Custom Worlds Advice
Fabric Seasons: Extras
Ad-Astra: Giselle Addon
YUNG's Better Ocean Monuments
spark
Applied Energistics 2 Wireless Terminals
No Chat Reports
Explorations
AdventureZ
Dynamic Trim
OpenBlocks Elevator (Fabric)
Eldritch End
Item Obliterator
Loot Integrations[Forge/Fabric]
Chat Heads
When Dungeons Arise - No Flying Structures
Almost Unified
Savage Ender Dragon[Forge/Fabric]
Fabric Waystones
Connectivity[Forge/Fabric]
Things
Indium
Shoulder Surfing Reloaded
LibZ
lazy-language-loader
Alternate Current
CleanCut
VanitySlots
Nether's Delight (Fabric)
TerraBlender
Luna
Athena
Iris Shaders
Tiny Skeletons
MC Dungeons Weapons
Entity Culling Fabric/Forge
Runelic
Create Slice & Dice
Better Fps - Render Distance[Fabric]
Visuality
Nether Depths Upgrade
Neruina - Ticking Entity Fixer
Decorative Blocks
Create: Estrogen
Mythic Upgrades
Combat Roll
MC Dungeons Armors
CC: Tweaked
Variant Barrels [Fabric | Forge]
Nicer Skies
Nature's Compass
Mouse Tweaks
Model Gap Fix
River Redux
Resourceful Config
Friends&Foes - Beekeeper Hut (Fabric)
Pehkui
Variant Composters [Fabric/Quilt]
Ocean'sÂ Delight
Better chunk loading[Forge/Fabric]
When Dungeons Arise - Spacing Tweaks
Your Options Shall Be Respected (YOSBR)
FTB Quests (Fabric)
Enchantment Descriptions
Puzzle
Better Trim Tooltips
Controlling
YetAnotherConfigLib
Simply Swords
Boat Item View
Reborn Core
FerriteCore
Mandala's GUI - Dark mode
Archon
Carrier
Friends&Foes (Fabric)
Repurposed Structures - Quilt/Fabric
SeasonHUD-Fabric
Repurposed Structures - Farmer's Delight Compat
HT's TreeChop
Industrial Revolution
More Armor Trims
Winterly
Necronomicon API
Eating Animation
Kibe
Variant Vanilla Blocks [Fabric | Forge]
Bewitchment
Variant Chests [Fabric | Forge]
Reacharound
Immersive Armors
FTB Teams (Fabric)
Drippy Loading Screen
Skin Layers 3D (Fabric/Forge)
FTB Library (Fabric)
Log Begone
Inventory Sorting
Mine Cells - Dead Cells Mod
Spell Power Attributes
Server Browser [Fabric/Forge]
Searchables
Caracal mob
Sound Physics Remastered
The Lost Castle
Better Beds
Chipped
Ping Wheel
Explorify
Architectury API
Double Doors
MEGA Cells
Deeper and Darker
Animal Feeding Trough
Reese's Sodium Options
Cherished Worlds
Better Than Mending
Better Smithing Table
End's Delight
TieredZ
Open Loader
ModernFix
Swampier Swamps (Fabric)
Roughly Enough Professions (REP)
Botarium
CreativeCore
Language Reload
Blur (Fabric)
Fabric API
Prominent
YUNG's Better Nether Fortresses
Stoneworks
YUNG's Better End Island
Promenade
Better Third Person
Farsight [Fabric]
Sodium Extra
Chef's Delight
Prominent UI Tweaks
Cloth Config API
Idwtialsimmoedm
Xaero's World Map
Vivecraft
Magnum Torch
Simply Houses
VoidZ
Prominent UI
Debugify
YUNG's Better Mineshafts
FancyMenu
Obscure API (Fabric)
ðŸŽƒ Insanity Shader
AzureLib Armor
MidnightLib
Extra Thicc Packets
Lightest Lamps
Twigs
cat_jam
Clickable advancements[Forge/Fabric]
FakerLib
Roughly Enough Items (REI)
Simple Discord RPC
Thermoo
Fabric Seasons
YUNG's Better Jungle Temples
Zenith Attributes
Too Fast
Better Statistics Screen
More Axolotl Variants API
Krypton
Resource Pack Overrides
Friends&Foes - Flowery Mooblooms (Fabric)
BetterNether
Expanded Delight
Jewelry (RPG Series)
Better Combat
VR Combat
oÏ‰o (owo-lib)
End Remastered
Resourceful Lib
Better Archeology
Not Enough Recipe Book [NERB]
Load My F***ing Tags
Prominent Create
Pig Pen Cipher
Alloy Forgery
More Mob Variants
Farmer's Knives [Fabric]
Runes
Clumps
Fish of Thieves
Presence Footsteps
Yeetus Experimentus
MmmMmmMmmMmm
Easy Anvils
KleeSlabs (Fabric Edition)
Inventory HUD+
Create: Steam 'n' Rails
Enhanced Boss Bars
BisectHosting Server Integration Menu
YUNG's Better Dungeons
VillagersPlus
Fish On The Line
Forge Config Screens
Recipe Essentials[Forge/Fabric]
Trinkets
Iceberg
Lootr
Open Parties and Claims
AppleSkin
Quartz Elevator
Zenith
Icarus
Variant Crafting Tables [Fabric | Quilt]
Modern Industrialization
Geophilic
Puzzles Lib
Ash API
Small Ships
Powah!
Blahaj (Fabric)
Do a Barrel Roll
Ad Astra
CIT Resewn
Tom's Simple Storage Mod
Spellblades and Such (Spell Engine)
AmbientSounds
Bartering Station
YUNG's Better Desert Temples
Dark Utilities
[ETF] Entity Texture Features
Towns and Towers
Let's Do: Beachparty
Pastel Shaders
YUNG's Better Witch Huts
Advanced Netherite
Moonlight Lib
Paladins & Priests (RPG Series)
Sodium
Furnish
Spell Engine
Paintings ++
Equipment Compare
Terralith
Naturalist
Kiwi ðŸ¥ (Fabric)
Passable Foliage ðŸŒ³ (Fabric)
Blockus
William Wythers' Overhauled Overworld
[Let's Do] Meadow
[Let's Do] Candlelight
[Let's Do] Bakery

**Comment by Cristelknight** [comment]
check if you are using the newest cristellib and wwee versions. sorry for replying so late

**Comment by Unbroke50** [comment]
**Same Thing Happened With Me But Custom Blocks**

**Comment by Unbroke50** [comment]
> BetterEnd Regions Unexplored Invocations (Spell Engine) Forge Config API Port More Totems of Undying Balm (Fabric Edition) Visual Workbench YUNG's API You Shall Not Spawn! [Forge/Fabric] CleanView (Fabric) Highlight Villager Names [EMF] Entity Model Features Mindful Darkness Cardinal Components API AutoTag Unsafe World Random Access Detector Cultural Delights [Fabric] NetherPortalFix (Fabric Edition) Grass Overhaul (Sod) Croptopia Aquamirae (Fabric) [Let's Do] Vinery ChoiceTheorem's Overhauled Village Pick Up Notifier When Dungeons Arise - Fabric! Server Performance - Smooth Chunk Save[Forge/Fabric] MixinTrace RightClickHarvest No See, No Tick Vein Mining Zoomify Diagonal Fences Let's Do: API Axolotl Bucket Fix bad packets Better Compatibility Checker The Bumblezone - Quilt/Fabric Better Advancements Block Swap Practical Plushies: Mobs Basket Dungeons and Taverns Artifacts Creeper Overhaul Carry On Complementary Shaders - Reimagined Structure Essentials[Forge/Fabric] Dark Enchanting Boat Break Fix [Neo/Forge/Fabric/Quilt] Cupboard Keybind Fix Cristel Lib Konkrete Projectile Damage Attribute Legendary Tooltips YUNG's Better Strongholds Not Enough Animations Redirector [Modern] Item Filters Supplementaries Bosses of Mass Destruction MVS - Moog's Voyager Structures Prism Philips Ruins Block Runner Fabric Seasons: Delight Compat Bookshelf More Axolotl Variants Mod Jade ðŸ” Repurposed Structures - Friends and Foes Compat Beacon Overhaul playerAnimator BCLib Trading Post Variant Bookshelves [Fabric/Quilt] AzureLib Collective Rare Ice Patchouli Frostiful CraterLib Fabric Seasons: Croptopia Compat Shield Overhaul [Fabric/Forge] Marium's Soulslike Weaponry Polymorph Auudio DEUF Refabricated Fabric Language Kotlin Traveler's Backpack Nether Chested Iron Chests: Restocked Create Crafts & Additions fix GPU memory leak[Forge/Fabric] Build Guide Applied Energistics 2 BetterTrims Mutant Monsters JamLib Dawn API Practical Plushies: Animals Archers (RPG Series) MES - Moog's End Structures Comforts StackDeobfuscator Oxidized Starter Kit All The Trims Overflowing Bars Mythic Mobs Audio Extension for FancyMenu Transparent Structory Farmer's Delight [Fabric] Pufferfish's Skills Windchimes Universal Graves Leaves Be Gone Xaero's Minimap The Graveyard (FABRIC) Hellion's Sniffer+ Lithium Falling Leaves Geckolib Tech Reborn Wizards (RPG Series) Mythic Mounts Disable Custom Worlds Advice Fabric Seasons: Extras Ad-Astra: Giselle Addon YUNG's Better Ocean Monuments spark Applied Energistics 2 Wireless Terminals No Chat Reports Explorations AdventureZ Dynamic Trim OpenBlocks Elevator (Fabric) Eldritch End Item Obliterator Loot Integrations[Forge/Fabric] Chat Heads When Dungeons Arise - No Flying Structures Almost Unified Savage Ender Dragon[Forge/Fabric] Fabric Waystones Connectivity[Forge/Fabric] Things Indium Shoulder Surfing Reloaded LibZ lazy-language-loader Alternate Current CleanCut VanitySlots Nether's Delight (Fabric) TerraBlender Luna Athena Iris Shaders Tiny Skeletons MC Dungeons Weapons Entity Culling Fabric/Forge Runelic Create Slice & Dice Better Fps - Render Distance[Fabric] Visuality Nether Depths Upgrade Neruina - Ticking Entity Fixer Decorative Blocks Create: Estrogen Mythic Upgrades Combat Roll MC Dungeons Armors CC: Tweaked Variant Barrels [Fabric | Forge] Nicer Skies Nature's Compass Mouse Tweaks Model Gap Fix River Redux Resourceful Config Friends&Foes - Beekeeper Hut (Fabric) Pehkui Variant Composters [Fabric/Quilt] Ocean'sÂ Delight Better chunk loading[Forge/Fabric] When Dungeons Arise - Spacing Tweaks Your Options Shall Be Respected (YOSBR) FTB Quests (Fabric) Enchantment Descriptions Puzzle Better Trim Tooltips Controlling YetAnotherConfigLib Simply Swords Boat Item View Reborn Core FerriteCore Mandala's GUI - Dark mode Archon Carrier Friends&Foes (Fabric) Repurposed Structures - Quilt/Fabric SeasonHUD-Fabric Repurposed Structures - Farmer's Delight Compat HT's TreeChop Industrial Revolution More Armor Trims Winterly Necronomicon API Eating Animation Kibe Variant Vanilla Blocks [Fabric | Forge] Bewitchment Variant Chests [Fabric | Forge] Reacharound Immersive Armors FTB Teams (Fabric) Drippy Loading Screen Skin Layers 3D (Fabric/Forge) FTB Library (Fabric) Log Begone Inventory Sorting Mine Cells - Dead Cells Mod Spell Power Attributes Server Browser [Fabric/Forge] Searchables Caracal mob Sound Physics Remastered The Lost Castle Better Beds Chipped Ping Wheel Explorify Architectury API Double Doors MEGA Cells Deeper and Darker Animal Feeding Trough Reese's Sodium Options Cherished Worlds Better Than Mending Better Smithing Table End's Delight TieredZ Open Loader ModernFix Swampier Swamps (Fabric) Roughly Enough Professions (REP) Botarium CreativeCore Language Reload Blur (Fabric) Fabric API Prominent YUNG's Better Nether Fortresses Stoneworks YUNG's Better End Island Promenade Better Third Person Farsight [Fabric] Sodium Extra Chef's Delight Prominent UI Tweaks Cloth Config API Idwtialsimmoedm Xaero's World Map Vivecraft Magnum Torch Simply Houses VoidZ Prominent UI Debugify YUNG's Better Mineshafts FancyMenu Obscure API (Fabric) ðŸŽƒ Insanity Shader AzureLib Armor MidnightLib Extra Thicc Packets Lightest Lamps Twigs cat_jam Clickable advancements[Forge/Fabric] FakerLib Roughly Enough Items (REI) Simple Discord RPC Thermoo Fabric Seasons YUNG's Better Jungle Temples Zenith Attributes Too Fast Better Statistics Screen More Axolotl Variants API Krypton Resource Pack Overrides Friends&Foes - Flowery Mooblooms (Fabric) BetterNether Expanded Delight Jewelry (RPG Series) Better Combat VR Combat oÏ‰o (owo-lib) End Remastered Resourceful Lib Better Archeology Not Enough Recipe Book [NERB] Load My F***ing Tags Prominent Create Pig Pen Cipher Alloy Forgery More Mob Variants Farmer's Knives [Fabric] Runes Clumps Fish of Thieves Presence Footsteps Yeetus Experimentus MmmMmmMmmMmm Easy Anvils KleeSlabs (Fabric Edition) Inventory HUD+ Create: Steam 'n' Rails Enhanced Boss Bars BisectHosting Server Integration Menu YUNG's Better Dungeons VillagersPlus Fish On The Line Forge Config Screens Recipe Essentials[Forge/Fabric] Trinkets Iceberg Lootr Open Parties and Claims AppleSkin Quartz Elevator Zenith Icarus Variant Crafting Tables [Fabric | Quilt] Modern Industrialization Geophilic Puzzles Lib Ash API Small Ships Powah! Blahaj (Fabric) Do a Barrel Roll Ad Astra CIT Resewn Tom's Simple Storage Mod Spellblades and Such (Spell Engine) AmbientSounds Bartering Station YUNG's Better Desert Temples Dark Utilities [ETF] Entity Texture Features Towns and Towers Let's Do: Beachparty Pastel Shaders YUNG's Better Witch Huts Advanced Netherite Moonlight Lib Paladins & Priests (RPG Series) Sodium Furnish Spell Engine Paintings ++ Equipment Compare Terralith Naturalist Kiwi ðŸ¥ (Fabric) Passable Foliage ðŸŒ³ (Fabric) Blockus William Wythers' Overhauled Overworld [Let's Do] Meadow [Let's Do] Candlelight [Let's Do] Bakery

Thats Too Much Mods Bro

**Comment by Cristelknight** [comment]
Bit late, but what version were you on? (Mc/wwee)
