### ISSUE TITLE
(Fabric 1.19.2) [V3.1.9.1] Crash On World Creation

### ISSUE THREAD

**Issue by Gentleman-Ghost** [Cristelknight/Expanded-Ecosphere#73]
Attempted to start a fresh world with default settings. The world is created, however the game instantly crashes. On attempting to load the same world, the game will crash. generating this error repeatedly: 
`java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / wythers:bamboo_swamp]=net.minecraft.class_1959@321a4937}]`

I have included the crash log. Hopefully someone can tell me if either I've done something terribly wrong, or the game is simply being unkind.

[crash-2023-11-19_21.04.26-server.txt](https://github.com/Cristelknight999/Expanded-Ecosphere/files/13404612/crash-2023-11-19_21.04.26-server.txt)

**Comment by DerCommander323** [comment]
I believe the problem lies here: https://github.com/Lothrazar/Cyclic/issues/2332

**Comment by Gentleman-Ghost** [comment]
I can see how that could be the case, as I am using one other Biome mod, but that doesn't really give me a way to fix the issue.

**Comment by Cristelknight** [comment]
you would have to re-arrange all features in the correct order. i did that in newer versions of wwoo. but i won't make a backport, because i currently have no time to work on this. also 1.19.2 is a bit outdated now
