### ISSUE TITLE
Make trees compatable with "Seperated Leaves" mod

### ISSUE THREAD

**Issue by Thezul1** [Cristelknight/Expanded-Ecosphere#75]
As it is now in the generation. The oak trees spawn with Azalea leaves and will not decay the correct way when using the mod Seperated Leaves. 

This mod will make all the leaves from the tree you cut down to decay without checking for being attached to another type of tree. But azalea leaves together with oak logs will not decay. I know its made like this to look pretty because of the green of azalea. But it makes other tree type mods incompatable with this amazing mod

**Comment by Cristelknight** [comment]
Sorry, but we won't change it. it's just a big part of the mod, that there are leaves combined with different types of woods

**Comment by Thezul1** [comment]
I understand.
