### ISSUE TITLE
"Remove ore blobs" config not working properly

### ISSUE THREAD

**Issue by AzrannAVANA** [Cristelknight/Expanded-Ecosphere#76]
![image](https://github.com/Cristelknight999/Expanded-Ecosphere/assets/112041895/6d6147a9-fa5c-4f85-b40c-e4e74cd09f24)

Ver 3.2.3
FORGE 1.20.1

I've tried to turn off the Remove ore blobs from the Mods config, but it didn't work. It actually didn't change the file data either...

Later I tried directly from the file, but as shown, it doesn't work too well in most cases it would seem. Only generating Granite.

This, as many players have reported, is making it more difficult to play Create.
You could go look for Andesite biomes yes, and these are fancy, but it's much more difficult to come across them in the rare explorations  than coming across them in caves in normal circumstances.

Thank you for your time, 
Create Fan #15268742

**Comment by Cristelknight** [comment]
![2023-12-10_14 43 05](https://github.com/Cristelknight999/Expanded-Ecosphere/assets/54945257/b19d83e8-c6ca-4264-822e-b61093eff4a4)
Config works just fine for me. Tbh i currently don't have time for this sadly. just trying to luck at a few issues at least

**Comment by AzrannAVANA** [comment]
Update: Nevermind on all this, I looked at the Spelunkery wiki today and found out they remove andesite.
So, it was that mod in the end, sorry for the trouble-
