### ISSUE TITLE
How do I remove the mod from an existing world?

### ISSUE THREAD

**Issue by morceaudebois** [Cristelknight/Expanded-Ecosphere#78]
Hi! I have a world on a server with Terraltih and Expanded Ecosphere. I'm looking to disable Expanded Ecosphere to generate some new terrain that would be Terralith only.

It seems like I can't disable the mod altogether and there isn't any option to disable its world generation while keeping it active. Is there a way to do it? I'd appreciate some help.

Thank you 😊

**Comment by Cristelknight** [comment]
You have to disable compatible mode and delete the overworld dimension file. You can find it in data/minecraft/dimension/
