### ISSUE TITLE
Regions Unexploed, WWOO 1.19.2

### ISSUE THREAD

**Issue by BenjaminBinkie** [Cristelknight/Expanded-Ecosphere#79]
I'm having this issue 

java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / minecraft:bamboo_jungle]=net.minecraft.world.level.biome.Biome@5543800c}, Reference{ResourceKey[minecraft:worldgen/biome / regions_unexplored:sparse_rainforest]=net.minecraft.world.level.biome.Biome@62a153d3}]

with the only mods being regions unexplored, terrablender, and WWOO on 1.19.2.

**Comment by Cristelknight** [comment]
Known issue. But there won't be 1.19.2 updates anymore
