### ISSUE TITLE
How to completely disable update check

### ISSUE THREAD

**Issue by charliez0** [Cristelknight/Expanded-Ecosphere#80]
Users in China cannot access the update link quickly and the startup process is likely to stuck for minutes

**Comment by LiAuTraver** [comment]
yeah me too. I'm in China and the cloud service cannot reach most of websites aboard. The update check of my server cost nearly 200 seconds and always results in timeout. (even change the config to `not notify`). Wish could have an option to disable the check.

**Comment by charliez0** [comment]
> yeah me too. I'm in China and the cloud service cannot reach most of websites aboard. The update check of my server cost nearly 200 seconds and always results in timeout. (even change the config to `not notify`). Wish could have an option to disable the check.

My workaround is to build a javaagent to block the internet connection

**Comment by Cristelknight** [comment]
Added a config option
