### ISSUE TITLE
Unable to make a superflat world while the mod is installed. (Forge 1.20.1)

### ISSUE THREAD

**Issue by Slickson77** [Cristelknight/Expanded-Ecosphere#81]
I was testing some stuff in my modpack and wanted to make a superflat world to do some designing and testing.  I wanted to make a superflat world to do this, but the option doesn't work on creating a new world and just gives you the William world generation.

**Comment by Cristelknight** [comment]
known issue. i think this is not fixable for a datapack. maybe i‘m wrong. when i have some time i will maybe look into it. does it work with other mods like terralith?

**Comment by Slickson77** [comment]
No idea, it was for a creative server, and once I removed your mod, it worked.  If you add it back in, terrain chunks start to load.  So I just left it out.
