### ISSUE TITLE
[Question] I need advice on translating biome names into another language.

### ISSUE THREAD

**Issue by etoGitHubDeniski** [Cristelknight/Expanded-Ecosphere#82]
Main question: Among the biomes that Expanded Ecosphere adds there are famous places from the real world. Comparing Minecraft origianl biome naming approach they try to give a descriptive name for the biome. Like "flower forest", not "Barbados flower forest" (I don't think they were inspired by this but just as an example). What would be the best way to translate this:
Ayers Rock ( "=" literal translation back to English)
1. "Айерс-Рок" = "Ayers Rock" - localized name of real place
2. "Гора Айерса" = "Ayers's rock" - literal translation
3. "Скальное образование Айерс-Рок" = "Ayers Rock rock formation" - more elegant and descriptive
4. "Гора Айерс-Рок" = "Ayers Rock rock" - short variant
5. "Красная гора" = "Red rock" - more vanilla like

If out of all the options there are no ones that definitely cannot be used, then I’ll think more. If any option is absolutely not suitable, then write. 

Tsingy Forest
1. "Цинги" = "Tsingy" - real place
2. "Лес Цинги" = "Tsingy forest" - direct translation
3. "Каменный лес Цинги" = "Tsingy Stone Forest" - good translation
4. "Каменный лес" = "Stone forest" - vanilla like 

Danakil Desert
1. "Пустыня Данакиль" = "Danakil desert" - verbatim
2. "Впадина Данакиль" = "Danakil depression"
3. "Гидротермальные источники Даллол" = "Dallol hydrothermal springs"
4. "Пустынные гидротермальные источники" = "Desert hydrothermal springs"
5. "Кислотные горячие источники" = "Acid hot springs"

I wrote down 2 more biomes as an example. On the one hand, I don’t want to add gags, on the other hand, I want to take naming and translate more seriously. Since this will be used by part of the community.

Second question:
ancient copper beech forest
is it ancient forest of copper beech or forest of ancient copper beech?

**Comment by etoGitHubDeniski** [comment]
As for naming, I think the best option is to translate it normally, and then write a separate resource pack with more vanilla names.

**Comment by Cristelknight** [comment]
If we would change it we only could change the translations and not the namespaces. Because if we would change those older worlds couldn‘t be loaded. In the mod version we could add datafixers, but in a datapack this isn‘t possible. Also this mod doesn‘t tries to be vanilla friendly, so idk if renaming the biomes would be in the spirit of the mod.
