### ISSUE TITLE
Where to find pumpkins?

### ISSUE THREAD

**Issue by EnderGirl1500** [Cristelknight/Expanded-Ecosphere#85]
Hi I'd like to know if pumpkins are generated with this mod... I haven't found them in days of gameplay, and I've created a new world in creative mode to look for them and still couldn't find them!

**Comment by Cristelknight** [comment]
In these:
![IMG_0940](https://github.com/Cristelknight999/Expanded-Ecosphere/assets/54945257/3c81961e-7b06-4b69-be74-064882ebb54f)
and these biomes:
![IMG_0938](https://github.com/Cristelknight999/Expanded-Ecosphere/assets/54945257/42f3e1a4-9fef-43ab-9a77-dc9d9fce198c)

**Comment by Cristelknight** [comment]
oh. also in these overhauled vanilla biomes:
![IMG_0942](https://github.com/Cristelknight999/Expanded-Ecosphere/assets/54945257/46190c39-275e-400a-8b93-84319be7c527)

**Comment by Cristelknight** [comment]
and in minecraft:snowy_beach. (didn‘t fit on the last screenshot)
