### ISSUE TITLE
WWOO conflicts for some reason with WWEE?

### ISSUE THREAD

**Issue by DivannKokos** [Cristelknight/Expanded-Ecosphere#86]
- Mod 'Expanded Ecosphere' (expanded_ecosphere) 3.2.4 conflicts with any version of mod 'William Wythers' Overhauled Overworld' (wwoo), which is present with the following versions: 2.0.0!
	 - While this won't prevent you from starting the game, the developer(s) of mod 'Expanded Ecosphere' (expanded_ecosphere) have found that this combination may cause issues. You should remove one of the mods or check for updates that resolve the issue.

server is starting and working, but it states this in log for some reason
is it okay?

**Comment by DivannKokos** [comment]
ooohhh... i think i get it
wwee is wwoo but with new biomes, yes?
so if want overhaul + new biomes
i need to keep only wwee?

**Comment by Cristelknight** [comment]
Yep. If you use both you kind of get the biomes twice. So you shouldn’t use both together.

**Comment by NovaLynxie** [comment]
Huh... was trying to figure out why they kept crashing when used together and about to create an issue report. But thankfully saw this, didn't know this could be the cause. Good to know its its own separate mod than an addon.
