### ISSUE TITLE
Trees generate with wool blocks in tropical rainforest biome

### ISSUE THREAD

**Issue by Halex000** [Cristelknight/Expanded-Ecosphere#87]
Version: 1.20.1
Mod loader: Fabric
Mod version: 3.2.4

The 2x2 trees with acacia logs generate with a block of wool in them in the tropical rainforest biome. Sorry for creating a new issue if this is intentional, I just wasn't sure if this was a block used to create the structure for the tree that was accidentally not removed. 

![2024-03-16_06 10 54](https://github.com/Cristelknight999/Expanded-Ecosphere/assets/95841600/5b7716e3-86c0-4f31-bd33-159080972ead)

**Comment by Cristelknight** [comment]
it is intended
