### ISSUE TITLE
I'd like to disable some biomes and I don't know how...

### ISSUE THREAD

**Issue by n64-Hypercube** [Cristelknight/Expanded-Ecosphere#88]
I'v seen in the configs the option to "disable a biome" with terrablender, but I can't make it work... I hope this is the good place for this kind of things, thanks.

**Comment by Cristelknight** [comment]
Could you maybe send your current config files?

**Comment by n64-Hypercube** [comment]
[forge-client.txt](https://github.com/Cristelknight999/Expanded-Ecosphere/files/14691733/forge-client.txt)
[terrablender.txt](https://github.com/Cristelknight999/Expanded-Ecosphere/files/14691734/terrablender.txt)
[fml.txt](https://github.com/Cristelknight999/Expanded-Ecosphere/files/14691735/fml.txt)

Here they are, I changed the files' extensions to upload them (from toml to txt). Do you also need default/server configs ?
(I precise ; the mods are : terrablender, cristel lib and WWOO)
anyways, thanks for this fast reply

**Comment by Cristelknight** [comment]
I meant the WWEE config. But also on which version are you on?

I also think you should just use this mod instead: https://modrinth.com/mod/biome-replacer
Read the description on how it works.

**Comment by troyere** [comment]
It only works at 100% with datapacks, not mods : 

> Note that this mod is intended mostly for replacing vanilla and datapack biomes. Biomes added using libraries like TerraBlender or Biolith cannot be replaced; you should use the mod's config to tweak or remove them instead.
> That said, this mod can safely be used alongside these libraries, and it's even possible to replace vanilla/datapack biomes with modded ones.

Still, being able to disable some biome is a great idea. An alternative maybe, just like in biome o plenty, a config file of booleans in order to enable/disable any biome would be great 😊

An example of the biome o plenty toggler :
![351593781-b4baeda7-e253-4996-8eb8-f2e752ebec74](https://github.com/user-attachments/assets/c704eef9-7524-4a27-a44c-fd97da72ee46)

**Comment by Cristelknight** [comment]
WWEE doesn't use terrablender (so you can use that mod just fine)

**Comment by Cristelknight** [comment]
And that's why we also can't just make a simple toggle config

**Comment by troyere** [comment]
Good to know hehe, let's hope there will be a BiomeReplacer version for 1.21 😉

**Comment by Cristelknight** [comment]
Doesn't seem so. You still can use the WWEE Config if you get it working.

**Comment by troyere** [comment]
Maybe it's better to make my own biome replacer

**Comment by Cristelknight** [comment]
Sure
