### ISSUE TITLE
[1.18.2] [Forge] Other World Types Don't Work 

### ISSUE THREAD

**Issue by Optify1** [Cristelknight/Expanded-Ecosphere#9]
Whenever I try to load a superflat world or single biome world, it just generates the default world type
![2022-11-22_11 22 11](https://user-images.githubusercontent.com/118838704/203369181-50c5abc0-159b-4047-9418-f03510654989.png)
I know you're not really supporting 1.18.2 anymore, but if it's a quick fix I'd appreciate it.

**Comment by Cristelknight** [comment]
Problem of Minecraft can’t be fixed.
