### ISSUE TITLE
DataPack for 1.20.3/4

### ISSUE THREAD

**Issue by ShaneBeee** [Cristelknight/Expanded-Ecosphere#91]
Hello

Im just wondering if there was a plan to release the data pack version for 1.20.3+?

**Comment by Cristelknight** [comment]
No there is no plan, because the development on WWEE is currently paused. But you can just copy the data from the mod into a new datapack. Most things should just work then

**Comment by ShaneBeee** [comment]
> No there is no plan, because the development on WWEE is currently paused. But you can just copy the data from the mod into a new datapack. Most things should just work then

thanks for letting me know.
I tried that and it failed. 
I did it in a single player game and it just did that error screen.
Ill try it again sometime and check the log and see if I can find a way around it

**Comment by ShaneBeee** [comment]
Just wanted to give an update, I got it to work.
had to change a few `"minecraft:grass"` -> `"minecraft:short_grass"`

**Comment by Cristelknight** [comment]
👍
