### ISSUE TITLE
[Enhancement]  Config menu

### ISSUE THREAD

**Issue by MMG778** [Cristelknight/Expanded-Ecosphere#98]
Please create a mod configuration menu or file for non-programming geniuses, so that we as players can configure all of WWEE's  and WWOO's features, item, biomes, etc, because I would like to use WWEE, WWOO with Terrestria, Nature's Spirit, Wilder Wild, Regions Unexplored and Terralith mod together, but there are certain biomes which I like more or don't like in others. For example Regions Unexplored, Wilder Wild, Terrestria, Nature's Spirit has an easily configurable config menu and config file. I hope this awesome thing can be done.

**Comment by Cristelknight** [comment]
this mod doesn't use terrablender, so such an easy config file is not possible. you can use the current config for most of this or the biome replacer mod.
